# Generated by Django 4.2.7 on 2023-12-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_published_at_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=1701596431.1893818),
        ),
    ]
